# Numpy

### learning to use Numpy

to install Numpy: pip3 install numpy
after you can import numpy or import numpy as >variable name< ie. 'np'

In [2]:
import numpy as np # imports the library numpy and names assigns it to the variable 'np'

In [3]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [4]:
a.dtype

dtype('int64')

In [6]:
a = np.array([1,2,3,4], dtype=np.float64)
a

array([1., 2., 3., 4.])

In [9]:
a.ndim, a.shape, a.size # handy to check data info

(1, (4,), 4)

In [16]:
b = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]], dtype=np.float64)
b

array([[1., 2., 3., 4., 5., 6.],
       [1., 2., 3., 4., 5., 6.]])

In [12]:
b.ndim, b.shape, b.size

(2, (2, 6), 12)

In [17]:
np.zeros((3,3), 'd') #ibland vill man skapa en tom array som vi fyller, kom ihåg att def datatyp, 
# 'd' är shorthand för dtype=double


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Numpy har många praktiska metoder för att fylla arrays. linspace() är ett bra exempel

In [26]:
np.linspace(0,10,num=21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [29]:
np.arange(0,21)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [32]:
np.random.standard_normal((5,5))

array([[ 1.32417242, -0.46299937,  0.92485609, -0.28978339, -0.89653902],
       [-0.77286025,  0.27549508,  0.35410421,  0.07623512, -0.67646078],
       [-0.50849694, -0.87096445,  0.91842728, -0.12235486, -1.28227713],
       [-0.75181586, -0.23961046, -1.53075403, -0.91424653, -0.22908337],
       [ 0.34067493, -0.27542182,  0.86286726,  0.83095968,  0.72304273]])

In [42]:
a = np.random.standard_normal((5,5))
b = np.random.standard_normal((5,5))

np.vstack((a,b))

array([[ 1.08346075,  0.22900526, -0.82798456,  0.20977795,  0.35389094],
       [ 1.6960803 ,  0.66053114, -1.25176684, -0.52427799,  0.25885478],
       [ 0.48410552,  0.09401279, -0.36380391, -0.75337944,  0.97410394],
       [ 2.16988833, -0.23409157,  1.25217493, -0.99856174,  1.39295271],
       [-0.37535693,  2.77205251,  1.51320116,  0.2538927 ,  0.00778937],
       [-1.05749701,  0.79424393, -1.17607929,  0.66558041, -0.8149617 ],
       [-0.45871718, -0.35775961, -1.50996332,  0.41630458, -1.27472052],
       [ 0.57800974, -0.07192652, -0.70965037,  2.67663441, -0.49932204],
       [ 0.97359325, -0.8415742 ,  1.33484971,  0.09771777,  1.26549805],
       [ 0.70234392, -0.18971654, -0.58581857, -0.41157391,  0.54302746]])

In [87]:
a = a.transpose()
a

array([[ 1.08346075,  0.22900526, -0.82798456,  0.20977795,  0.35389094],
       [ 1.6960803 ,  0.66053114, -1.25176684, -0.52427799,  0.25885478],
       [ 0.48410552,  0.09401279, -0.36380391, -0.75337944,  0.97410394],
       [ 2.16988833, -0.23409157,  1.25217493, -0.99856174,  1.39295271],
       [-0.37535693,  2.77205251,  1.51320116,  0.2538927 ,  0.00778937]])

In [88]:
np.savetxt('example.npy',a
          )